services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neonomaly
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - neonomaly-network
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neonomaly
    networks:
      - neonomaly-network

networks:
  neonomaly-network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
  minio_data: